### ISSUE TITLE
Complex types don't show when not using repeated

### ISSUE THREAD

**Issue by ronan-skyscanner** [Neopallium/lua-pb#22]
Hi,

I have found that using the _optional_ or _required_ properties for complex types prevents them from being serialised properly.

Modifying the Person example to make the PhoneNumber optional:
```
message Person {
  required string name = 1;
  required int32 id = 2;
  optional string email = 3;

  enum PhoneType {
    MOBILE = 0;
    HOME = 1;
    WORK = 2;
  }

  message PhoneNumber {
    required string number = 1;
    optional PhoneType type = 2 [default = HOME];
  }

  optional PhoneNumber phone = 4;
}
```

Running example_person.lua gives this output:
```
name: "John Doe"
id: 1234
email: "jdoe@example.com"
phone {
}
Encode person message to binary.
lua: example_person.lua:21: attempt to get length of local 'bin' (a boolean value)
stack traceback:
	example_person.lua:21: in main chunk
	[C]: ?
```

**Comment by Neopallium** [comment]
The `msg:Serialize()` method is returning an error, because the `number` field of `PhoneNumber` is required.  The `example_person.lua` code would need to be changed to correctly initialize the `phone` field of the `Person` message.

This is not really a bug, since lua-pb doesn't support assigning an array of messages to an `optional` field.
